import type { Metadata } from "next";
import "./globals.css";
import { fontVariables } from "@/app/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontVariables} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
