import type { Metadata } from "next";
import "./globals.scss";
import { fontVariables } from "@/app/fonts";
import MouseFollower from "mouse-follower";
import gsap from "gsap";

MouseFollower.registerGSAP(gsap);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const cursor = new MouseFollower({
//   container: document.body,
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${fontVariables} antialiased dark`}>{children}</body>
    </html>
  );
}
