import type { Metadata } from "next";
import "./globals.scss";
import { fontVariables } from "@/app/fonts";
import CursorProvider from "@/app/CursorProvider";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${fontVariables}`}>
      <body className={`antialiased dark ${fontVariables}`}>
        <CursorProvider>{children}</CursorProvider>
      </body>
    </html>
  );
}
